CREATE USER smooch_user WITH PASSWORD '111';
CREATE DATABASE smooch_devel;
CREATE DATABASE smooch_test;
ALTER USER smooch_user WITH SUPERUSER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO smooch_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to smooch_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to smooch_user;